.gitignore, README.md, docker/README.md, docker/local-config/docker-compose.yml, docker/local-config/zeebe.cfg.toml, docker/run
See https://github.com/zeebe-io/zeebe-simple-monitor/issues/25#issuecomment-437475081
Add docker folder in order to have other subfolders if needed
Add new docker-compose for running zeebe broker with zeebe-simple-monitor
Add bash script in order to automate every steps
Update README in order to explain "How to run" with docker
Please let me know if I can improve anything else!
=> 25 Improve docker-compose

docker/local-config/docker-compose.yml
fixes #48 
This adds `io.zeebe.monitor.connectionString=zeebe:26500` to the environment of docker-compose to allow the Simple Monitor to communicate with the broker.
=> Environmentalise broker connection in docker-compose

docker/run
The docker run script could not remove the containers as it was meant in the script. This was causing problems because of the database schema changes.
=> Bugfix for Issue #59 Docker compose fails with 0.15.0

docker/README.md
The url in this readme was wrong
Remove "connect to broker zeebe:26500" because it's not needed.
=> Update url in docker/readme

app/src/main/resources/public/js/app.js
The current grammar is not quite right. Alternatively this could be worded as:
"An instance of this workflow has changed."
=> Correct grammar of workflow instance change notifications

src/main/java/io/zeebe/monitor/rest/ViewController.java
Fixing the issue with double slash `//` in the context-path. 
closes #219
=> Add trailing slash to context path only if missing

src/main/java/io/zeebe/monitor/rest/ViewController.java, src/main/resources/templates/components/table-pagination.html
* show the first and last page
* show up to two previous and next pages
Based and inspired by #227.
=> [UI] Advanced pagination

src/main/java/io/zeebe/monitor/zeebe/ZeebeNotificationService.java
* handle tailing slash in the context path for the websocket destination
=> Fix the destination of the websocket notifications

src/main/java/io/zeebe/monitor/rest/ViewController.java
* replace the backticks in the BPMN because they are used in the HTML to enclose the content of the BPMN
closes #235
=> Show BPMN diagram if the BPMN contains a backtick 

.github/workflows/deploy.yml, pom.xml
Simplify the build/deploy process by using the project version as the docker image tag. 
Avoid tagging the docker image as `latest` because it seems not recommended.
=> build(docker): use project version as docker image tag

pom.xml, src/main/java/io/zeebe/monitor/rest/ExceptionHandler.java, src/main/java/io/zeebe/monitor/rest/ViewController.java, src/main/java/io/zeebe/monitor/rest/WhitelabelProperties.java, src/main/resources/templates/error.html, src/test/java/io/zeebe/monitor/rest/ViewControllerTest.java
Please refer to https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/279 and https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/282. I'm creating a new PR, to circumvent an issue with cla-assistant. See comments over there.
In short, I'd like to improve the error handling by establishing a dedicated ExceptionHandler.
=> Fix error page if context path is configured

README.md, UPGRADE.md, src/main/java/io/zeebe/monitor/entity/ElementInstanceEntity.java, src/main/java/io/zeebe/monitor/entity/VariableEntity.java, src/main/java/io/zeebe/monitor/repository/ElementInstanceRepository.java, src/main/java/io/zeebe/monitor/repository/VariableRepository.java, src/main/java/io/zeebe/monitor/zeebe/importers/ProcessAndElementImporter.java, src/main/java/io/zeebe/monitor/zeebe/importers/VariableImporter.java, src/test/java/io/zeebe/monitor/repository/ElementInstanceRepositoryTest.java, src/test/java/io/zeebe/monitor/repository/TestContextJpaConfiguration.java, src/test/java/io/zeebe/monitor/repository/VariableRepositoryTest.java, src/test/java/io/zeebe/monitor/repository/ZeebeRepositoryTest.java, src/test/java/io/zeebe/monitor/rest/ViewControllerTest.java, src/test/java/io/zeebe/monitor/zeebe/importers/ProcessAndElementImporterTest.java, src/test/java/io/zeebe/monitor/zeebe/importers/VariableImporterTest.java, src/test/resources/application-junittest.yaml
Based on the discussion in PR #280,
this is the actual bug fix for issue #278.
This PR depends on #284, because of the author's preference to split #280 into separate PRs.
This bug fix uses the approach of transient creation of an ID, based on PartitionID and Position.
Also, tests are added, to show how it works.
The duplicate check is implemented again.
=> bugfix for issue #278 - rework duplicate check element instances and variables

src/main/java/io/zeebe/monitor/rest/ViewController.java, src/main/resources/templates/components/bpmn-diagram.html
Since Zeebe Simple Monitor was build to support developers on local testing etc.,
I found myself in situations, where e.g. the process definition was no more available in the database.
This caused the BPMN diagram renderer to fail with exception and was confusing for me as user of Simple Monitor.
Unfortunately, I can't trace back, what caused the fact, that the process was not available, but this would be worth another PR, right? ;)
This PR just makes the renderer more robust in case of in-consistent data.
Additionally, I did replace the ```throw new RuntimeException()``` in the ViewController
with proper ```throw new ResponseStatusException()``` which will also improve/relate to PR #286 "Feature/error handler2".
Just for the record, the error can be reproduced, if someone deletes the …
=> Add error handling in case of process definition not found

src/main/java/io/zeebe/monitor/rest/ProcessDto.java, src/main/resources/public/js/app.js, src/main/resources/templates/components/table-pagination.html, src/main/resources/templates/instance-list-view.html, src/main/resources/templates/instance-list.html, src/main/resources/templates/process-list-view.html
* show the deployment time of processes
* add sorting of processes by deployment time
* add sorting of process instances by start time 
closes #275
=> I can sort processes and process instances

UPGRADE.md, src/main/java/io/zeebe/monitor/entity/ElementInstanceEntity.java, src/main/java/io/zeebe/monitor/entity/ErrorEntity.java, src/main/java/io/zeebe/monitor/entity/IncidentEntity.java, src/main/java/io/zeebe/monitor/entity/JobEntity.java, src/main/java/io/zeebe/monitor/entity/MessageSubscriptionEntity.java, src/main/java/io/zeebe/monitor/entity/TimerEntity.java
This PR add missing indices to columns, which are used frequently.
I have a Zeebe Simple Monitor running and observed decreasing responsiveness/response times of the UI,
because I did some performance testing. In my scenario, I had 3 million process instances created.
This led to timeouts in the DB lookup. 
Adding indices not only solved the problem but also made the UI significantly more responsive.
Any feedback is welcome.
=> adding indices to tables improves responsiveness 

src/main/java/io/zeebe/monitor/rest/ExceptionHandler.java, src/main/java/io/zeebe/monitor/rest/ProcessInstanceResource.java, src/main/java/io/zeebe/monitor/rest/ui/ErrorMessage.java, src/main/java/io/zeebe/monitor/rest/ui/ProcessInstanceNotification.java, src/main/java/io/zeebe/monitor/rest/ui/ZeebeClusterNotification.java, src/main/java/io/zeebe/monitor/zeebe/ZeebeNotificationService.java, src/main/resources/public/js/app.js, src/main/resources/templates/layout/header.html, src/test/java/io/zeebe/monitor/rest/AbstractViewOrResourceTest.java, src/test/java/io/zeebe/monitor/rest/ProcessInstanceResourceTest.java, src/test/java/io/zeebe/monitor/rest/ViewControllerTest.java
Using Simple Monitor during development is somehow awkward because e.g. BPMN errors during deployment,
or actions like "resolve incident" do not show underlying Zeebe errors.
This PR attempts to improve this by a) enabling multiple errors shown at once and b) actively pushing ZeebeClientException messages to the UI.
* add: forwarding/pushing ZeebeClient errors to the web UI
* add: allow multiple errors, info, and success messages displayed at once in the UI
* add: Test for ProcessInstanceResource
* add: extended ExceptionHandler to push ZeebeClientExceptions to the UI 
* change: introduce abstract test class for ViewController and Resource tests
* change: when during incident resolving the job can't be changed, there's still an attempt to resolve the incident
* fix: closing error panel …
=> feat(UI): forward Zeebe client exceptions to the web UI

src/main/resources/application.yaml
There was a change in Zeebe configuration, that ```contactPoint``` was deprecated by https://github.com/camunda-cloud/zeebe/pull/5345
this PR just uses ```gatewayAddress``` instead.
=> fix(zeebe-client): use gatewayAddress instead of deprecated contactPoint

src/main/java/io/zeebe/monitor/ZeebeSimpleMonitorApp.java
while developing and testing with Zeebe, the PostgreSQL DB sometimes is out of synch and makes Simple Monitor fall flat,
during rendering the mustache template. This includes the custom /error page, which is still a white page, even with all exception handlers in place.
This PR simply places a ⍰ character as default, so rendering passes through and just the special character is placed,
where the missing variable was used. This can look like this:
I know this default value violates a bit the "fail fast" principle.
But I found it more annoying to analyze broken HTML/screenshots and search for exceptions in the log.
E.g. recently a field 'elementId' was not populated ... and its used multiple times - so the hunt for the broken template did start :/
This approach seems to be more indicative …
=> feat(ui): show ⍰ as default value in case of missing variables in mustache templates

src/main/resources/public/js/app.js, src/main/resources/templates/components/bpmn-diagram.html, src/main/resources/templates/process-detail-view.html
This is a simple but helpful feature, it allows the download of the (shown) BPMN definition.
Tested in Firefox, Safari, and Chrome (all latest/recent versions).
Any feedback is welcome.
=> feature(ui): download button for the BPMN definition

.github/workflows/build.yml, .github/workflows/deploy.yml, pom.xml
Just a proposal ... since I'm not aware of what "we" are waiting for ;)
- ✅ Tests are green.
- ✅ Application runs (in Docker Compose and from IDE)
- ✅ Annoying Hazelcast warning about reflection to "sun.nio.ch.SelectorImpl" is gone.
- ✅ Docker image with Java 17.0.2 is used (tested with mvn/jib)
- ✅ Github workflow is adopted
=> chore(deps): switch to Java 17

src/main/resources/templates/instance-detail-view.html
* the process instance page links to sub-pages for variables, audit, etc.
* the links to the sub-pages doesn't apply the context-path like the other links
closes #374
=> Fix process instance details page for different contexts

pom.xml, src/main/resources/application.yaml
This commit adds basic prometheus instrumentation by making use of micrometer.
Exposed metrics are available at: `http://host:port/actuator/prometheus`
<details>
<summary>Prometheus metrics</summary>
```
jvm_memory_committed_bytes{application="zeebe-simple-monitor",area="heap",id="G1 Old Gen",} 1.09051904E8
jvm_memory_committed_bytes{application="zeebe-simple-monitor",area="heap",id="G1 Eden Space",} 8.8080384E7
jvm_memory_committed_bytes{application="zeebe-simple-monitor",area="nonheap",id="Metaspace",} 9.1684864E7
jvm_memory_committed_bytes{application="zeebe-simple-monitor",area="heap",id="G1 Survivor Space",} 1.2582912E7
jvm_memory_committed_bytes{application="zeebe-simple-monitor",area="nonheap",id="CodeHeap 'profiled nmethods'",} 1.4286848E7 …
```
=> Add basic prometheus instrumentation

src/main/java/io/zeebe/monitor/rest/JobResource.java
* the command to fail a job resulted in an error in the Zeebe client
* fix the command by not activating the job before marking it as failed
=> fix: Fail a job

pom.xml
just a minor fix, which tackles these Maven warnings ...
```
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework.boot:spring-boot-starter-actuator:jar -> duplicate declaration of version (?) @ line 115, column 21
[WARNING] 'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. @ line 251, column 21
```
=> build: fixes Maven warnings (duplicate entry and missing version)

README.md, docker/docker-compose.yml, pom.xml, src/test/java/io/zeebe/monitor/repository/ZeebeApplicationMysqlTest.java, src/test/resources/application-mysql-docker.yaml
Add the mysql driver as a dependency.
As discusse in issue: https://github.com/camunda-community-hub/zeebe-simple-monitor/issues/337
Based on previouse work to add the Postgres driver: https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/307
=> feat: Bundle a MySQL driver

src/main/resources/public/js/app.js
Just a minor thing, but since the app.js loads in every view, 
there was a JS error, when the screen model does not contain the required field, like in 'errors' for example.
Error was:
```
app.js:714 Uncaught ReferenceError: RAW_BPMN_RESOURCE is not defined
at checkIfBpmnExistsOrDisableDownloadButton (app.js:714:5)
```
=> fix: RAW_BPMN_RESOURCE is not defined

src/test/resources/payment.bpmn, src/test/resources/ship-parcel.bpmn
tested with Zeebe 8.0.6, some errors did occur during deployment and are now fixed.
- task correlation key must be defined with equal sign (=)
- flow, conditional expressions must be defined with equal sign (=)
- comparison must use single equal sing (=) instead of two (==)
=> fix: bpmn demo files

src/main/java/io/zeebe/monitor/rest/ProcessResource.java, src/test/java/io/zeebe/monitor/Demo.java
trivial one, just replacing the two occurrences.
=> fix: replace deprecated newDeployCommand() with newDeployResourceCommand()

src/main/resources/application.yaml
because since spring-boot-autoconfigure:2.7.3, this field was moved
see https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/mustache/MustacheProperties.html
=> fix deprecation "expose-request-attributes"

README.md, src/main/java/io/zeebe/monitor/WebSocketConfig.java, src/main/java/io/zeebe/monitor/ZeebeSimpleMonitorApp.java, src/main/resources/application.yaml
Related to https://github.com/camunda-community-hub/zeebe-simple-monitor/issues/476
=> Adds cors support

pom.xml, src/main/java/io/zeebe/monitor/querydsl/IncidentEntityPredicatesBuilder.java, src/main/java/io/zeebe/monitor/repository/IncidentRepository.java, src/main/java/io/zeebe/monitor/rest/IncidentsViewController.java, src/main/resources/public/js/app.js, src/main/resources/templates/incident-list-view.html, src/main/resources/templates/layout/footer.html
implements #438 
- introducing new dependencies for QueryDSL
- reasoning QueryDSL is well supported with the Spring JPA framework and eases the filtering of various attributes
- there's a bug fix for popper.js, since the import was broken (visible in JS console of Chrome, when clicking a drop-down menu, created with bootstrap and then there was the error message, that popper.js was missing)
- on-top of the ticket, I do introduce sorting of error type and process id to further assist in finding incidents
=> feat(ui): incident view filtering by process id and time

src/main/java/io/zeebe/monitor/entity/ElementInstanceEntity.java
I'd like to suggest additional indices on ElementInstance.
That table is queried from the monitor, and if you have some amount of data in the table, the query would run ages.
This PR adds some indices.
Fixes https://github.com/camunda-community-hub/zeebe-simple-monitor/issues/583, supersedes #584.
=> Add indices to ElementIndices to speed up queries

pom.xml
* Bump zeebe-hazelcast-connector to version 1.4.0
* Fixes issue https://github.com/camunda-community-hub/zeebe-simple-monitor/issues/541
=> Bump Zeebe Hazelcast Connector to 1.4.0

.github/workflows/build.yml, .github/workflows/deploy.yml
Also, use more generic version "@v1" instead pinned hashes
=> chore(build): fix `Error: Input required and not supplied: distribution`

pom.xml, src/main/java/io/zeebe/monitor/ZeebeSimpleMonitorApp.java
this relates to the fact that Spring Boot 3.2.x did implement a new boot-loader code for uber jars.
See https://github.com/spring-projects/spring-boot/issues/38636 for details.
=> fix #659 implement a workaround to fix UnsupportedOperationException

docker/docker-compose.yml
The docker compose file does not work, because the image
ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.7.1
does not exist in ghcr.io
=> fix: ghcr.io/.../zeebe-simple-monitor:2.7.1 does not exist

README.md, src/main/java/io/zeebe/monitor/zeebe/hazelcast/HazelcastImportService.java, src/main/java/io/zeebe/monitor/zeebe/hazelcast/HazelcastStateService.java, src/main/java/io/zeebe/monitor/zeebe/protobuf/importers/ErrorProtobufImporter.java, src/main/java/io/zeebe/monitor/zeebe/protobuf/importers/HazelcastStateService.java, src/main/java/io/zeebe/monitor/zeebe/protobuf/importers/IncidentProtobufImporter.java, src/main/java/io/zeebe/monitor/zeebe/protobuf/importers/JobProtobufImporter.java, src/main/java/io/zeebe/monitor/zeebe/protobuf/importers/MessageProtobufImporter.java, src/main/java/io/zeebe/monitor/zeebe/protobuf/importers/MessageSubscriptionProtobufImporter.java, src/main/java/io/zeebe/monitor/zeebe/protobuf/importers/ProcessAndElementProtobufImporter.java, src/main/java/io/zeebe/monitor/zeebe/protobuf/importers/TimerProtobufImporter.java, src/main/java/io/zeebe/monitor/zeebe/protobuf/importers/VariableProtobufImporter.java, src/test/java/io/zeebe/monitor/repository/TestContextJpaConfiguration.java
This PR introduces some metrics about the import process.
These are collected when:
- items are stored in the database
- when reading from Hazelcast's RingBuffer.
In addition, it replaces field-based autowiring with the recommended constructor autowiring.
=> Export metrics about the import process

README.md, docker/docker-compose.yml, pom.xml
This PR superseeds #775 (including some updates in README and docker-compores)
---
This PR updates the dependencies to
* latest Zeebe 8.5 (explicitly not 8.6 due to the license change)
* QueryDSL:
* The apt-maven-plugin has been archived https://github.com/querydsl/querydsl/issues/3436#issuecomment-1328637362
* Redis Exporter 1.0.1
* Spring Boot for JDK 23 compatibility
* set JRE-23 as runtime for the docker container (JIB configuration)
* Drop the v prefix from the release version
The Hazelcast setup runs locally for me, "works-on-my-machine".
The UnitTests succeed.
Unfortunately, I cannot test the Redis/Kafka integration, the docker-compose is outdated.
I did not add any new features, especially not in the Protobuf parsers. This is only a dependency update.
- [n/a] the tests are alle …
=> Update dependencies for Camunda 8.5 / JDK 23 v2
